export const formElementsListIcon: Record<string, string> = {
  Checkbox: 'circle-check',
  DatePicker: 'calendar',
  H1: 'heading-1',
  H2: 'heading-2',
  H3: 'heading-3',
  P: 'text',
  Input: 'text-cursor-input',
  OTP: 'binary',
  MultiSelect: 'list',
  Password: 'lock',
  RadioGroup: 'list-todo',
  Select: 'square-chevron-down',
  Separator: 'minus',
  Slider: 'sliders-horizontal',
  Switch: 'toggle-right',
  Textarea: 'letter-text',
  ToggleGroup: 'toggle-left',
  FileUpload: 'file-up',
};
